version: "3.5"

services:

  database:
    image: postgres:11
    hostname: database
    container_name: database
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: showcase
      POSTGRES_PASSWORD: showcase
    volumes:
      - ./postgres-init-user-db.sh:/docker-entrypoint-initdb.d/postgres-init-user-db.sh
    networks:
      - novatectcshowcase

  manufacturedomain:
    image: novatec/technologyconsulting-showcase-manufacturedomain:latestlocal
    hostname: manufacturedomain
    container_name: manufacturedomain
    environment:
      HTTP_PORT: 9080
      HTTPS_PORT: 9443
      SUPPLIER_PURCHASE_URL: http://supplierdomain:9080/supplierdomain/supplier/purchase/
      SUPPLIER_USER: orderer
      SUPPLIER_PASSWORD: pwd
      DB_HOST: database
      DB_USER: manufacture_user
      DB_PASSWORD: manufacture_pass
      DB_PORT: 5432
      DB_SCHEMA: public
      DB_NAME: manufacture_db
    ports:
      - 9080:9080
    networks:
      - novatectcshowcase

  orderdomain:
    image: novatec/technologyconsulting-showcase-orderdomain:latestlocal
    hostname: orderdomain
    container_name: orderdomain
    environment:
      HTTP_PORT: 9080
      HTTPS_PORT: 9443
      MANUFACTURE_WORKORDER_URL: http://manufacturedomain:9080/manufacturedomain/workorder/
      MANUFACTURE_USER: testuser
      MANUFACTURE_PASSWORD: pwd
      DB_HOST: database
      DB_USER: order_user
      DB_PASSWORD: order_pass
      DB_PORT: 5432
      DB_SCHEMA: public
      DB_NAME: order_db
    ports:
      - 9081:9080
    networks:
      - novatectcshowcase

  supplierdomain:
    image: novatec/technologyconsulting-showcase-supplierdomain:latestlocal
    hostname: supplierdomain
    container_name: supplierdomain
    environment:
      HTTP_PORT: 9080
      HTTPS_PORT: 9443
      MANUFACTURE_DELIVER_URL: http://manufacturedomain:9080/manufacturedomain/component/deliver/
      MANUFACTURE_USER: testuser
      MANUFACTURE_PASSWORD: pwd
      DB_HOST: database
      DB_USER: supplier_user
      DB_PASSWORD: supplier_pass
      DB_PORT: 5432
      DB_SCHEMA: public
      DB_NAME: supplier_db
    ports:
      - 9082:9080
    networks:
      - novatectcshowcase

  driver:
    image: novatec/technologyconsulting-showcase-driver:latestlocal
    hostname: driver
    container_name: driver
    environment:
      GATLING_BASEURL_SUPPLIERDOMAIN: "http://supplierdomain:9080"
      GATLING_BASEURL_ORDERDOMAIN: "http://orderdomain:9080"
      GATLING_BASEURL_MANUFACTUREDOMAIN: "http://manufacturedomain:9080" 
      GATLING_NR_USERS: 1
      GATLING_MAX_DURATION: 1
      GATLING_RAMPUP_TIME: 10
      GATLING_NR_USERS_AT_ONCE: 1   
    networks:
      - novatectcshowcase

networks:
  novatectcshowcase:
      driver: bridge
      name: novatectcshowcase

