#!/bin/bash

# setup basic TC-Showcase database for local development
# should be replaced with Flyway in each application

set -e

DATABASES='order manufacture supplier'

for i in $DATABASES; do
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE USER "${i}_user" WITH PASSWORD '${i}_pass';
        CREATE DATABASE "${i}_db";
        GRANT ALL PRIVILEGES ON DATABASE "${i}_db" TO "${i}_user";
EOSQL
done

psql -v ON_ERROR_STOP=1 --username "supplier_user" --dbname "supplier_db" <<-EOSQL
CREATE TABLE S_PURCHASE_ORDER (PO_NUMBER INTEGER NOT NULL, PO_SENT_DATE DATE, PO_SITE_ID INTEGER NOT NULL, PO_START_DATE TIMESTAMP, PO_SUPP_ID INTEGER, PO_VERSION INTEGER, PRIMARY KEY (PO_NUMBER));
CREATE TABLE S_PURCHASE_ORDERLINE (POL_NUMBER INTEGER NOT NULL, POL_PO_ID INTEGER NOT NULL, POL_LOCATION INTEGER NOT NULL, POL_LEADTIME INTEGER, POL_MESSAGE VARCHAR(100), POL_QTY INTEGER, POL_BALANCE DECIMAL(12,2), POL_P_ID VARCHAR(20), POL_DELDATE DATE, POL_VERSION INTEGER, PRIMARY KEY (POL_NUMBER, POL_PO_ID));
CREATE TABLE S_SUPP_COMPONENT (SC_P_ID VARCHAR(20) NOT NULL, SC_SUPP_ID INTEGER NOT NULL, SC_DEL_DATE INTEGER, SC_DISCOUNT DECIMAL(38), SC_PRICE DECIMAL(12,2), SC_QTY INTEGER, SC_VERSION INTEGER, PRIMARY KEY (SC_P_ID, SC_SUPP_ID));
CREATE TABLE S_COMPONENT (COMP_ID VARCHAR(20) NOT NULL, CONTAINER_SIZE INTEGER, COMP_COST DECIMAL(12,2), COMP_DESC VARCHAR(100), LEAD_TIME INTEGER, COMP_NAME VARCHAR(10), QTY_DEMANDED INTEGER, QTY_ON_ORDER INTEGER, COMP_SITE_ID INTEGER, COMP_UNIT VARCHAR(10), COMP_VERSION INTEGER, PRIMARY KEY (COMP_ID));
CREATE TABLE S_SUPPLIER (SUPP_ID INTEGER NOT NULL, SUPP_CONTACT VARCHAR(25), SUPP_NAME VARCHAR(16), SUPP_REPLY_URL VARCHAR(128), SUPP_VERSION INTEGER, SUPP_WS_URL VARCHAR(128), SUPP_CITY VARCHAR(20), SUPP_COUNTRY VARCHAR(10), SUPP_PHONE VARCHAR(16), SUPP_STATE VARCHAR(2), SUPP_STREET1 VARCHAR(20), SUPP_STREET2 VARCHAR(20), SUPP_ZIP VARCHAR(9), PRIMARY KEY (SUPP_ID));
ALTER TABLE S_PURCHASE_ORDERLINE ADD CONSTRAINT FK_S_PURCHASE_ORDERLINE_POL_PO_ID FOREIGN KEY (POL_PO_ID) REFERENCES S_PURCHASE_ORDER (PO_NUMBER);
CREATE TABLE U_SEQUENCES (S_ID VARCHAR(50) NOT NULL, S_NEXTNUM DECIMAL(38), PRIMARY KEY (S_ID));
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME));
EOSQL

psql -v ON_ERROR_STOP=1 --username "manufacture_user" --dbname "manufacture_db" <<-EOSQL
CREATE TABLE M_WORKORDER (WO_NUMBER INTEGER NOT NULL, WO_ASSEMBLY_ID VARCHAR(20), WO_COMP_QTY INTEGER, WO_DUE_DATE TIMESTAMP, WO_LOCATION INTEGER NOT NULL, WO_OL_ID INTEGER, WO_ORIG_QTY INTEGER, WO_O_ID INTEGER, WO_START_DATE TIMESTAMP, WO_STATUS INTEGER, WO_VERSION INTEGER, PRIMARY KEY (WO_NUMBER));
CREATE TABLE M_PARTS (P_ID VARCHAR(20) NOT NULL, P_TYPE INTEGER, P_DESC VARCHAR(100), P_HIMARK INTEGER, P_LOMARK INTEGER, P_NAME VARCHAR(35), P_PLANNER INTEGER, P_IND INTEGER, P_REV VARCHAR(6), P_VERSION INTEGER, PRIMARY KEY (P_ID));
CREATE TABLE M_INVENTORY (IN_P_ID VARCHAR(20) NOT NULL, IN_LOCATION INTEGER NOT NULL, IN_ACC_CODE INTEGER, IN_ACT_DATE TIMESTAMP, IN_ORDERED INTEGER, IN_QTY INTEGER, IN_VERSION INTEGER, PRIMARY KEY (IN_P_ID, IN_LOCATION));
CREATE TABLE M_BOM (B_COMP_ID VARCHAR(20) NOT NULL, B_LINE_NO INTEGER NOT NULL, B_ASSEMBLY_ID VARCHAR(20) NOT NULL, B_ENG_CHANGE VARCHAR(10), B_OPS_DESC VARCHAR(100), B_OPS INTEGER, B_QTY INTEGER, B_VERSION INTEGER, PRIMARY KEY (B_COMP_ID, B_LINE_NO, B_ASSEMBLY_ID));
ALTER TABLE M_INVENTORY ADD CONSTRAINT FK_M_INVENTORY_IN_P_ID FOREIGN KEY (IN_P_ID) REFERENCES M_PARTS (P_ID);
ALTER TABLE M_BOM ADD CONSTRAINT FK_M_BOM_B_ASSEMBLY_ID FOREIGN KEY (B_ASSEMBLY_ID) REFERENCES M_PARTS (P_ID);
CREATE TABLE U_SEQUENCES (s_id VARCHAR(50) NOT NULL, s_nextnum DECIMAL(38), PRIMARY KEY (s_id));
EOSQL

psql -v ON_ERROR_STOP=1 --username "order_user" --dbname "order_db" <<-EOSQL
CREATE TABLE O_CUSTOMERINVENTORY (CI_CUSTOMERID INTEGER NOT NULL, CI_ID INTEGER NOT NULL, CI_QUANTITY INTEGER, CI_VALUE DECIMAL(12,2), CI_VERSION INTEGER, CI_ITEMID VARCHAR(20), PRIMARY KEY (CI_CUSTOMERID, CI_ID));
CREATE TABLE O_ITEM (I_ID VARCHAR(20) NOT NULL, I_CATEGORY INTEGER NOT NULL, I_DESC VARCHAR(100), I_DISCOUNT DECIMAL(6,4), I_NAME VARCHAR(35), I_PRICE DECIMAL(12,2), I_VERSION INTEGER, PRIMARY KEY (I_ID));
CREATE TABLE O_CUSTOMER (C_ID INTEGER NOT NULL, C_BALANCE DECIMAL(12,2), C_CONTACT VARCHAR(25), C_CREDIT VARCHAR(2), C_CREDIT_LIMIT DECIMAL(12,2), C_FIRST VARCHAR(16), C_LAST VARCHAR(16), C_SINCE DATE, C_VERSION INTEGER, C_YTD_PAYMENT DECIMAL(12,2), C_CITY VARCHAR(20), C_COUNTRY VARCHAR(10), C_PHONE VARCHAR(16), C_STATE VARCHAR(2), C_STREET1 VARCHAR(20), C_STREET2 VARCHAR(20), C_ZIP VARCHAR(9), PRIMARY KEY (C_ID));
CREATE TABLE O_ORDERS (O_ID INTEGER NOT NULL, O_DISCOUNT DECIMAL(12,2), O_ENTRY_DATE TIMESTAMP, O_OL_CNT INTEGER, O_SHIP_DATE DATE, O_STATUS INTEGER, O_TOTAL DECIMAL(12,2), O_VERSION INTEGER, O_C_ID INTEGER, PRIMARY KEY (O_ID));
CREATE TABLE O_ORDERLINE (OL_O_ID INTEGER NOT NULL, OL_ID INTEGER NOT NULL, OL_MSRP DECIMAL(12,2), OL_QTY INTEGER, OL_SHIP_DATE DATE, OL_STATUS INTEGER, OL_TOTAL_VALUE DECIMAL(12,2), OL_VERSION INTEGER, OL_I_ID VARCHAR(20), PRIMARY KEY (OL_O_ID, OL_ID));
ALTER TABLE O_CUSTOMERINVENTORY ADD CONSTRAINT FK_O_CUSTOMERINVENTORY_CI_CUSTOMERID FOREIGN KEY (CI_CUSTOMERID) REFERENCES O_CUSTOMER (C_ID);
ALTER TABLE O_ORDERS ADD CONSTRAINT FK_O_ORDERS_O_C_ID FOREIGN KEY (O_C_ID) REFERENCES O_CUSTOMER (C_ID);
ALTER TABLE O_ORDERLINE ADD CONSTRAINT FK_O_ORDERLINE_OL_O_ID FOREIGN KEY (OL_O_ID) REFERENCES O_ORDERS (O_ID);
CREATE TABLE U_SEQUENCES (S_ID VARCHAR(50) NOT NULL, S_NEXTNUM DECIMAL(38), PRIMARY KEY (S_ID));
EOSQL